import os
import sys


def translate(translation):
    
    # Coco dataset
    translation = translation.replace("laptop", "лаптоп")
    translation = translation.replace("person", "човек")
    translation = translation.replace("bicycle", "колело")
    translation = translation.replace("car", "кола")
    translation = translation.replace("motorbike", "мотор")
    translation = translation.replace("aeroplane", "самолет")
    translation = translation.replace("bus", "автобус")
    translation = translation.replace("train", "влак")
    translation = translation.replace("truck", "камион")
    translation = translation.replace("boat", "лодка")
    translation = translation.replace("traffic light", "светофар")
    translation = translation.replace("fire hydrant", "пожарен кран")
    translation = translation.replace("stop sign", "знак стоп")
    translation = translation.replace("parking meter", "паркометър")
    translation = translation.replace("bench", "пейка")
    translation = translation.replace("bird", "птица")
    translation = translation.replace("cat", "котка")
    translation = translation.replace("dog", "куче")
    translation = translation.replace("horse", "кон")
    translation = translation.replace("sheep", "овца")
    translation = translation.replace("cow", "крава")
    translation = translation.replace("elephant", "слон")
    translation = translation.replace("bear", "мечка")
    translation = translation.replace("zebra", "зебра")
    translation = translation.replace("giraffe", "жираф")
    translation = translation.replace("backpack", "раница")
    translation = translation.replace("umbrella", "чадър")
    translation = translation.replace("handbag", "дамска чанта")
    translation = translation.replace("tie", "вратовръзка")
    translation = translation.replace("suitcase", "куфар")
    translation = translation.replace("frisbee", "фризби")
    translation = translation.replace("skis", "ски")
    translation = translation.replace("snowboard", "сноуборд")
    translation = translation.replace("sports ball", "спортна топка")
    translation = translation.replace("kite", "хвърчило")
    translation = translation.replace("baseball bat", "бейзболна бухалка")
    translation = translation.replace("baseball glove", "бейзболна ръкавица")
    translation = translation.replace("skateboard", "скейтборд")
    translation = translation.replace("surfboard", "дъска за сърф")
    translation = translation.replace("tennis racket", "тенис ракета")
    translation = translation.replace("bottle", "шише")
    translation = translation.replace("wine glass", "чаша за вино")
    translation = translation.replace("cup", "чаша")
    translation = translation.replace("fork", "вилица")
    translation = translation.replace("knife", "нож")
    translation = translation.replace("spoon", "лъжица")
    translation = translation.replace("bowl", "купа")
    translation = translation.replace("banana", "банан")
    translation = translation.replace("apple", "ябълка")
    translation = translation.replace("sandwich", "сандвич")
    translation = translation.replace("orange", "портокал")
    translation = translation.replace("broccoli", "броколи")
    translation = translation.replace("carrot", "морков")
    translation = translation.replace("hot dog", "хотдог")
    translation = translation.replace("pizza", "пица")
    translation = translation.replace("donut", "донът")
    translation = translation.replace("cake", "торта")
    translation = translation.replace("chair", "стол")
    translation = translation.replace("sofa", "диван")
    translation = translation.replace("pottedplant", "засадено растение")
    translation = translation.replace("potted plant", "засадено растение")
    translation = translation.replace("bed", "легло")
    translation = translation.replace("diningtable", "маса за хранене")
    translation = translation.replace("dining table", "маса за хранене")
    translation = translation.replace("toilet", "тоалетна")
    translation = translation.replace("tvmonitor", "телевизионен монитор")
    translation = translation.replace("tv monitor", "телевизионен монитор")
    translation = translation.replace("laptop", "лаптоп")
    translation = translation.replace("mouse", "мишка")
    translation = translation.replace("remote", "дистанционно")
    translation = translation.replace("keyboard", "клавиатура")
    translation = translation.replace("cell phone", "телефон")
    translation = translation.replace("microwave", "микровълнова")
    translation = translation.replace("oven", "печка")
    translation = translation.replace("toaster", "тостер")
    translation = translation.replace("sink", "мивка")
    translation = translation.replace("refrigerator", "хладилник")
    translation = translation.replace("book", "книга")
    translation = translation.replace("clock", "часовник")
    translation = translation.replace("vase", "ваза")
    translation = translation.replace("scissors", "ножици")
    translation = translation.replace("teddy bear", "плюшено мече")
    translation = translation.replace("hair drier", "сешоар")
    translation = translation.replace("toothbrush", "четка за зъби")
    
    # H_Pos
    translation = translation.replace('right', 'в дясно има ')
    translation = translation.replace('left', 'в ляво има ')
    translation = translation.replace('center', 'в центъра има ')
    
    # W_Pos
    translation = translation.replace('top', 'горе ')
    translation = translation.replace('mid', 'по средата ')
    translation = translation.replace('bottom', 'долу ')
    
    # Colors
    translation = translation.replace("red", "червено")
    translation = translation.replace("yellow", "жълто")
    translation = translation.replace("blue", "синьо")
    translation = translation.replace("brown", "кафяво")
    translation = translation.replace("orange", "оранжево")
    translation = translation.replace("green", "зелено")
    translation = translation.replace("violet", "виолетово")
    translation = translation.replace("black", "черно")
    translation = translation.replace("pink", "розово")
    translation = translation.replace("white", "бяло")
    translation = translation.replace("gray", "сиво")
    
    print(translation)
    return translation